#!/usr/bin/env python3
"""
Report duplicate Gaia source_ids in the built database.

Read-only.

    python3 db/scripts/check_duplicates.py           # exits 1 if anything is wrong
    DB_HOST=localhost DB_PORT=5432 python3 ... --quiet

A Gaia DR3 source_id names one physical source, so two rows sharing one are normally the
same star recorded twice. The interesting part is that "normally" is doing real work, and
getting this check right meant separating two populations that look identical in a
GROUP BY count:

**Duplicates this pipeline created (never acceptable).** cns5.csv and gcns.csv are both
generated by cross-matching against the live database, and both were generated from the
same pre-supplement snapshot. Neither could see what the other would insert, so 2,598 of
the 2,665 stars CNS5 introduced as new were introduced as new by GCNS as well -- the same
physical star inserted twice in one build, roughly 30 minutes apart. Measured example:
gaia 1005873614080407296 arrived as ids 5000426 and 6069717, with RA agreeing to nine
decimal places and identical magnitude and spectral type.

**Duplicates inherited from AT-HYG (legitimate).** About 1,167 groups are real close
binaries: Tycho-2 resolved both components, Gaia DR3 recorded one source, and AT-HYG kept
both rows. 88% of them carry hard evidence -- distinct Tycho-2 identifiers and/or explicit
component designations such as GJ 314A / GJ 314B, or Graffias / Graffias B. Merging those
would delete real stars, so the project's decision (2026-07-31) is to keep them.

So the invariant is not "no duplicates" but "no duplicate we created", which is what lets
this survive an AT-HYG release that changes the binary count while still failing the
moment an import reintroduces the bug. The same invariant is asserted at build time in
db/sql/07_import_gcns.sql; this script is the after-the-fact report.
"""
import argparse
import os
import sys

try:
    import psycopg2
except ImportError:
    sys.exit("psycopg2 is required: pip install -r db/scripts/requirements.txt")

# Rows with an id at or above this were INSERTed by a supplement import rather than coming
# from AT-HYG. match_cns5.py allocates from 5000000 and match_gcns.py from 6000000.
FIRST_IMPORTED_ID = 5000000

# Duplicate groups inherited from AT-HYG 4.0, measured 2026-07-31 after the import guards
# landed. Tracked as a baseline rather than required to be zero because they are real
# binaries; the check fails if the number GROWS, which would mean a new catalog release
# brought more, or that something started creating them again by another route.
KNOWN_INHERITED_BASELINE = 1166


def classify_group(ids):
    """
    Classify one set of athyg ids sharing a Gaia source_id.

    Returns "created" if any row in the group was inserted by a supplement import, else
    "inherited". A group is only blamed on the pipeline if the pipeline actually put a row
    in it -- a pair of AT-HYG rows is not ours to explain.

    Pure so it can be tested without a database; the SQL guard in 07_import_gcns.sql
    expresses the same rule.
    """
    if any(i >= FIRST_IMPORTED_ID for i in ids):
        return "created"
    return "inherited"


def summarise(groups):
    """
    @param groups mapping of gaia source_id -> list of athyg ids
    @return (created, inherited) counts
    """
    created = inherited = 0
    for ids in groups.values():
        if len(ids) < 2:
            continue
        if classify_group(ids) == "created":
            created += 1
        else:
            inherited += 1
    return created, inherited


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quiet", action="store_true", help="only report problems")
    args = parser.parse_args()

    conn = psycopg2.connect(
        host=os.environ.get("DB_HOST", "hygmap-db"),
        port=int(os.environ.get("DB_PORT", "5432")),
        dbname=os.environ.get("DB_NAME", "hygmap"),
        user=os.environ.get("DB_USERNAME", "hygmap_user"),
        password=os.environ.get("DB_PASSWORD", "hygmap_pass"),
    )

    problems = 0
    with conn.cursor() as cur:
        cur.execute(
            "SELECT gaia, array_agg(id) FROM athyg WHERE gaia IS NOT NULL"
            " GROUP BY gaia HAVING count(*) > 1"
        )
        groups = {gaia: ids for gaia, ids in cur.fetchall()}
        created, inherited = summarise(groups)

        if created:
            problems += created
            print(f"FAIL  {created:>6,}  Gaia ids duplicated by a row this pipeline inserted")
            print(
                "              -> a supplement import created a star that already existed;"
                " check the NOT EXISTS guards on the 'new' inserts in"
                " 06_import_cns5.sql and 07_import_gcns.sql"
            )
            offenders = [
                g for g, ids in groups.items() if classify_group(ids) == "created"
            ][:3]
            print(f"              -> example source_id(s): {', '.join(offenders)}")
        elif not args.quiet:
            print("ok         0  Gaia ids duplicated by a row this pipeline inserted")

        if inherited > KNOWN_INHERITED_BASELINE:
            problems += inherited - KNOWN_INHERITED_BASELINE
            print(
                f"FAIL  {inherited:>6,}  Gaia ids duplicated within AT-HYG"
                f" (baseline {KNOWN_INHERITED_BASELINE},"
                f" so {inherited - KNOWN_INHERITED_BASELINE} new)"
            )
            print(
                "              -> these are normally real close binaries sharing one Gaia"
                " source; confirm that before raising the baseline"
            )
        elif not args.quiet:
            print(
                f"ok  {inherited:>6,}  Gaia ids duplicated within AT-HYG"
                f" (inherited, baseline {KNOWN_INHERITED_BASELINE})"
            )
            print(
                "              -> real close binaries: Tycho-2 resolves both components,"
                " Gaia DR3 records one source. Kept deliberately."
            )

        # A Gaia source is a single point on the sky. Two rows sharing an id but sitting
        # far apart are not a binary at all -- AT-HYG 4.0 has one such case, where a
        # Cepheus star carries a Leo star's source_id, distance, proper motion and radial
        # velocity. Wide separation is the signature that distinguishes a bad
        # cross-match from a genuine unresolved pair.
        cur.execute(
            """
            WITH d AS (SELECT gaia FROM athyg WHERE gaia IS NOT NULL
                       GROUP BY gaia HAVING count(*) > 1),
                 p AS (SELECT a.gaia, min(a.id) lo, max(a.id) hi
                       FROM athyg a JOIN d USING (gaia) GROUP BY a.gaia)
            SELECT count(*) FROM p
            JOIN athyg l ON l.id = p.lo JOIN athyg h ON h.id = p.hi
            WHERE l.ra IS NOT NULL AND h.ra IS NOT NULL
              AND degrees(2*asin(least(1, sqrt(
                    power(sin(radians(h.dec - l.dec)/2), 2) +
                    cos(radians(l.dec))*cos(radians(h.dec))*
                    power(sin(radians(h.ra - l.ra)/2), 2))))) > 1.0
            """
        )
        (far_apart,) = cur.fetchone()
        if far_apart:
            problems += far_apart
            print(f"FAIL  {far_apart:>6,}  rows sharing a Gaia id but over 1 degree apart")
            print(
                "              -> not a binary; the source_id is attached to the wrong"
                " star. Decode the id's HEALPix pixel (source_id // 2**35, nside 4096)"
                " to find which row it really belongs to, then retract the other with"
                " clear_gaia in db/data/athyg_overrides.csv"
            )
        elif not args.quiet:
            print("ok         0  rows sharing a Gaia id but over 1 degree apart")

    conn.close()
    if problems:
        print(f"\n{problems:,} problem(s) need attention")
        return 1
    if not args.quiet:
        print("\nno duplicate-identifier problems found")
    return 0


if __name__ == "__main__":
    sys.exit(main())
